export const TASKS = [
  {
    id: 'RT-014',
    title: 'Build a Personal Portfolio Website',
    description: 'Create and deploy your own portfolio website to showcase your projects and skills.',
    difficulty: 'Intermediate',
    hours: '3-4 hrs',
    status: 'in_progress',
    due: 'Due in 4 days',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    skills: ['React Native', 'Web Dev', 'UI/UX Design', 'Tailwind'],
    challengeSteps: [
      'Design hero & project showcase layout.',
      'Implement smooth dark/light theme switching.',
      'Deploy site & verify responsive performance.',
    ],
  },
  {
    id: 'RT-013',
    title: 'Design a Signup Flow for a Fintech App',
    description: 'Wireframe a signup flow that gets users onboarded in under 60 seconds.',
    difficulty: 'Beginner',
    hours: '2-3 hrs',
    status: 'completed',
    due: 'Completed 3 days ago',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    skills: ['UI/UX', 'Figma', 'Prototyping', 'User Research'],
    challengeSteps: [
      'Wireframe 3-step seamless onboarding.',
      'Add biometric auth UI & haptic cues.',
      'Conduct quick 60-second usability test.',
    ],
  },
  {
    id: 'RT-015',
    title: 'Write a Product Launch Email',
    description: 'Draft a launch email for a new productivity app targeting students.',
    difficulty: 'Beginner',
    hours: '1-2 hrs',
    status: 'locked',
    due: 'Unlocks next week',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    skills: ['Copywriting', 'Marketing', 'Product Strategy'],
    challengeSteps: [
      'Identify key hook & benefit statements.',
      'Structure email body with clear CTA.',
      'Refine tone for student audience engagement.',
    ],
  },
];